# -*- coding: utf-8 -*-
"""Copy of Final AO3 Wrapped Tracker 2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KGJ6jNc9UP4yk6ETPz6YjSxezm6fXdCl

# SETUP!
PRESS RUN ON THE NEXT CELL OF CODE AND SIGN IN WITH GOOGLE.
"""

import os

OUTPUT_DIR = "C:\Users\agemp\Documents\ao3_wrapped_website\output"
os.makedirs(OUTPUT_DIR, exist_ok=True)

import sys
!{sys.executable} -m pip install requests beautifulsoup4 pandas

import sys
!{sys.executable} -m pip install reportlab

import sys
!{sys.executable} -m pip install Pillow

ASSETS_DIR = "C:\Users\agemp\Documents\ao3_wrapped_website\static"

os.listdir(ASSETS_DIR)

# ---------------------------------------------------PNG FORMATTING-----------------------------------------------------
from PIL import ImageFont

FONT_PATH = "C:\Users\agemp\Documents\ao3_wrapped_website\static\LeagueSpartan.otf"

font_144 = ImageFont.truetype(FONT_PATH, 144)
font_120 = ImageFont.truetype(FONT_PATH, 120)
font_80  = ImageFont.truetype(FONT_PATH, 80)
font_72  = ImageFont.truetype(FONT_PATH, 72)
font_40  = ImageFont.truetype(FONT_PATH, 40)
font_37  = ImageFont.truetype(FONT_PATH, 37)
font_35  = ImageFont.truetype(FONT_PATH, 35)
font_32  = ImageFont.truetype(FONT_PATH, 32)

from PIL import ImageDraw

def hex_to_rgb(hex_color):
    hex_color = hex_color.lstrip("#")
    return tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))


def draw_centered_text(draw, box, text, font, fill):
    x1, y1, x2, y2 = box
    bbox = draw.textbbox((0, 0), text, font=font)
    w = bbox[2] - bbox[0]
    h = bbox[3] - bbox[1]
    x = x1 + (x2 - x1 - w) // 2
    y = y1 + (y2 - y1 - h) // 2
    draw.text((x, y), text, font=font, fill=fill)


def draw_wrapped_centered_text(draw, box, text, font, fill, line_spacing=10):
    """
    Draws text wrapped and centered inside a bounding box.
    box = (x1, y1, x2, y2)
    """
    x1, y1, x2, y2 = box
    max_width = x2 - x1
    max_height = y2 - y1

    words = text.split()
    lines = []
    current_line = ""

    # Build lines word by word
    for word in words:
        test_line = current_line + (" " if current_line else "") + word
        bbox = draw.textbbox((0, 0), test_line, font=font)
        line_width = bbox[2] - bbox[0]

        if line_width <= max_width:
            current_line = test_line
        else:
            lines.append(current_line)
            current_line = word

    if current_line:
        lines.append(current_line)

    # Measure total height of all lines
    line_heights = []
    total_text_height = 0

    for line in lines:
        bbox = draw.textbbox((0, 0), line, font=font)
        h = bbox[3] - bbox[1]
        line_heights.append(h)
        total_text_height += h

    total_text_height += line_spacing * (len(lines) - 1)

    # Starting Y so the block is vertically centered
    y = y1 + (max_height - total_text_height) // 2

    # Draw each line centered horizontally
    for line, h in zip(lines, line_heights):
        bbox = draw.textbbox((0, 0), line, font=font)
        w = bbox[2] - bbox[0]
        x = x1 + (max_width - w) // 2
        draw.text((x, y), line, font=font, fill=fill)
        y += h + line_spacing

# -----------------------------------------EXTRACT_FIC_DATA FUNCTION-------------------------------------------------------------
import requests
from bs4 import BeautifulSoup

def extract_fic_data(url):
    """
    Extracts detailed information from an AO3 fanfiction URL.

    Args:
        url (str): The URL of the AO3 fanfiction.

    Returns:
        dict: A dictionary containing extracted fanfiction data.
              Returns an empty dictionary if extraction fails.
    """
    fic_data = {
        'url': url,
        'title': None, # Added for title extraction
        'word_count': None,
        'ratings': [],
        'archive_warnings': [],
        'category': [],
        'fandoms': [],
        'relationships': [],
        'characters': [],
        'free_form_tags': [],
        'authors': [] # Added authors key
    }

    try:
        response = requests.get(url)
        response.raise_for_status()  # Raise an HTTPError for bad responses (4xx or 5xx)
        soup = BeautifulSoup(response.text, 'html.parser')

        # Extract Title
        title_h2 = soup.find('h2', class_='title')
        if title_h2:
            fic_data['title'] = title_h2.get_text(strip=True)

        # Find the work meta group where most of the data is located
        work_meta = soup.find('dl', class_='work meta group')

        if work_meta:
            # Helper function to extract list items from a dd tag
            def extract_list_items(dd_tag, class_name):
                items = []
                dd_element = dd_tag.find('dd', class_=class_name)
                if dd_element:
                    for li in dd_element.find_all('li'):
                        items.append(li.get_text(strip=True))
                return items

            # Word Count
            words_dd = work_meta.find('dd', class_='words')
            if words_dd:
                try:
                    fic_data['word_count'] = int(words_dd.get_text(strip=True).replace(',', ''))
                except ValueError:
                    fic_data['word_count'] = None

            # Ratings
            fic_data['ratings'] = extract_list_items(work_meta, 'rating')

            # Archive Warnings
            fic_data['archive_warnings'] = extract_list_items(work_meta, 'warning')

            # Category (e.g., M/M, F/F)
            fic_data['category'] = extract_list_items(work_meta, 'category')

            # Fandoms
            fic_data['fandoms'] = extract_list_items(work_meta, 'fandom')

            # Relationships
            fic_data['relationships'] = extract_list_items(work_meta, 'relationship')

            # Characters
            fic_data['characters'] = extract_list_items(work_meta, 'character')

            # Other General Tags (Freeform)
            fic_data['free_form_tags'] = extract_list_items(work_meta, 'freeform')

        # Extract Author(s)
        # Changed from soup.find('div', class_='byline') to soup.find(class_='byline') for broader matching
        byline_element = soup.find(class_='byline')
        if byline_element:
            authors = byline_element.find_all('a', rel='author')
            for author_tag in authors:
                fic_data['authors'].append(author_tag.get_text(strip=True))

    except requests.exceptions.RequestException as e:
        print(f"Request failed for {url}: {e}")
    except Exception as e:
        print(f"An error occurred during extraction for {url}: {e}")

    return fic_data

print(f"\nDefined 'extract_fic_data' function.")

# -----------------------------------------CREATE CSV-------------------------------------------------------------
import pandas as pd
import ast # For safely evaluating string representations of lists

# Define the full path for the fanfiction tracker CSV in Google Drive
tracker_file_path = "C:\Users\agemp\Documents\ao3_wrapped_website\data\AO3_fanfiction_tracker.csv"

# List of columns that should contain lists (to be handled with ast.literal_eval)
list_columns = ['authors', 'ratings', 'archive_warnings', 'category', 'fandoms', 'relationships', 'characters', 'free_form_tags']

# Check if the tracker file already exists
if os.path.exists(tracker_file_path):
    print(f"Tracker file found at: {tracker_file_path}. Loading data...")
    fic_tracker_df = pd.read_csv(tracker_file_path)

    # Convert string representations of lists back into actual Python lists
    for col in list_columns:
        if col in fic_tracker_df.columns:
            # Use a lambda function to apply literal_eval, handling potential NaN or non-string values
            fic_tracker_df[col] = fic_tracker_df[col].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
    print("Data loaded successfully.")
else:
    print(f"No tracker file found at: {tracker_file_path}. Creating a new empty tracker.")
    # Create a new empty DataFrame with the specified columns, including 'title'
    fic_tracker_df = pd.DataFrame(columns=[
        'url', 'title', 'word_count', 'authors', 'ratings', 'archive_warnings', 'category',
        'fandoms', 'relationships', 'characters', 'free_form_tags'
    ])
    print("Empty DataFrame created.")

# -----------------------------------------ADD_FIC_TO_TRACKER FUNCTION-------------------------------------------------------------
def add_fic_to_tracker(url):
    """
    Extracts fanfiction data from a given URL, adds it to the global fic_tracker_df,
    and saves the updated DataFrame to Google Drive.

    Args:
        url (str): The URL of the AO3 fanfiction to track.
    """
    global fic_tracker_df, tracker_file_path, list_columns

    # 2. Extract fic data
    print(f"Extracting data for: {url}")
    fic_details = extract_fic_data(url)

    if not fic_details or fic_details.get('word_count') is None:
        print(f"Could not extract data for {url}. It might be invalid or inaccessible. Skipping.")
        return

    # 3. Convert dictionary to pandas Series and ensure column order
    # Use reindex to ensure the Series has all columns of fic_tracker_df, filling missing with NaN
    new_fic_series = pd.Series(fic_details).reindex(fic_tracker_df.columns)

    # 4. Append new Series as a new row to the DataFrame
    # Using pd.concat for appending a single row (recommended over df.append for newer pandas versions)
    fic_tracker_df = pd.concat([fic_tracker_df, pd.DataFrame([new_fic_series])], ignore_index=True)

    # 5. Save the updated DataFrame to CSV
    # Convert list columns back to string representations for CSV saving
    df_to_save = fic_tracker_df.copy()
    for col in list_columns:
        if col in df_to_save.columns:
            df_to_save[col] = df_to_save[col].apply(lambda x: str(x) if isinstance(x, list) else x)

    df_to_save.to_csv(tracker_file_path, index=False)
    print(f"Successfully added fic from {url} to tracker. Updated tracker saved to {tracker_file_path}.")

print("Defined `add_fic_to_tracker` function.")

# ---------------------------------------------------BUTTON FORMATTING-------------------------------------------------
import ipywidgets as widgets
from IPython.display import display

# 2. Create a widgets.Textarea instance
ao3_url_textarea = widgets.Textarea(
    value='',
    placeholder='Enter AO3 URLs here (one per line)',
    description='AO3 URLs:',
    layout={'width': '500px', 'height': '200px'}
)

# 3. Create a widgets.Button instance
add_fic_button = widgets.Button(
    description='Add Fic(s)',
    button_style='success' # 'success', 'info', 'warning', 'danger' or ''
)

# 4. Create a widgets.Output instance
output_widget = widgets.Output()

# 5. Create a widgets.Button instance for generating wrapped report
generate_wrapped_button = widgets.Button(
    description='Generate Wrapped Report', # Changed description
    button_style='info'
)

print("Initialized ipywidgets components: ao3_url_textarea, add_fic_button, generate_wrapped_button, output_widget.")

# define add fic button
def on_add_fic_button_clicked(button):
    with output_widget:
        output_widget.clear_output()
        print("Processing URLs...")

        urls_raw = ao3_url_textarea.value.strip().split('\n')
        urls = [url.strip() for url in urls_raw if url.strip()]

        if not urls:
            print("No URLs entered in the textarea.")
            return

        for url in urls:
            print(f"\nAttempting to add: {url}")
            # The add_fic_to_tracker function already prints its own success/failure messages
            # We just need to ensure these prints happen within the output_widget context.
            add_fic_to_tracker(url)

        print("\nFinished processing all entered URLs.")
        ao3_url_textarea.value = '' # Clear the textarea after processing

print("Defined `on_add_fic_button_clicked` function.")

# define generate wrapped report button handler
def on_generate_wrapped_button_clicked(button):
    with output_widget:
        output_widget.clear_output()
        print("Generating AO3 Wrapped Report...")

        # Reload fic_tracker_df from CSV to ensure latest data is used
        global fic_tracker_df, tracker_file_path, list_columns, ASSETS_DIR, OUTPUT_DIR
        # Include font variables and helper functions as globals for clarity, though they are already global
        global font_144, font_120, font_80, font_72, font_40, font_37, font_35, font_32, hex_to_rgb, draw_centered_text, draw_wrapped_centered_text

        if not os.path.exists(tracker_file_path):
            print("Error: Tracker file not found. Please add fics first.")
            return

        fic_tracker_df = pd.read_csv(tracker_file_path)
        # Convert string representations of lists back into actual Python lists
        for col in list_columns:
            if col in fic_tracker_df.columns:
                fic_tracker_df[col] = fic_tracker_df[col].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
        print("Latest tracker data loaded successfully for report generation.")

        if fic_tracker_df.empty:
            print("No fics in the tracker to generate a report. Please add fics first.")
            return

        # -------------------------------------------COMPILE DATA------------------------------------------------------------------------
        # WORD COUNT
        total_word_count = fic_tracker_df['word_count'].sum()
        total_unique_fics = fic_tracker_df['url'].nunique()
        average_words_per_day = round(total_word_count / 365)

        print(f"Total Word Count: {total_word_count}")
        print(f"Total Unique Fics: {total_unique_fics}")
        print(f"Average Words Per Day (based on 365 days): {average_words_per_day}")

        # LONGEST FIC
        longest_fic = fic_tracker_df.loc[fic_tracker_df['word_count'].idxmax()]

        longest_fic_title = longest_fic['title']
        longest_fic_word_count = longest_fic['word_count']
        longest_fic_url = longest_fic['url']
        longest_fic_author = longest_fic['authors'][0] if longest_fic['authors'] else 'N/A'

        print(f"\nLongest Fanfiction:\nTitle: {longest_fic_title}\nWord Count: {longest_fic_word_count}\nAuthor: {longest_fic_author}\nURL: {longest_fic_url}")

        # FAVORITE FIC
        from collections import Counter
        url_counts = fic_tracker_df['url'].value_counts()
        most_frequent_url = url_counts.idxmax()
        favorite_fic_visits = url_counts.max()

        favorite_fic = fic_tracker_df[fic_tracker_df['url'] == most_frequent_url].iloc[0]

        favorite_fic_title = favorite_fic['title']
        favorite_fic_word_count = favorite_fic['word_count']
        favorite_fic_author = favorite_fic['authors'][0] if favorite_fic['authors'] else 'N/A'
        favorite_fic_url = favorite_fic['url']

        print(f"\nFavorite Fanfiction (Most Frequent):\nTitle: {favorite_fic_title}\nWord Count: {favorite_fic_word_count}\nAuthor: {favorite_fic_author}\nURL: {favorite_fic_url}\nVisits: {favorite_fic_visits}")

        # TOP 5 AUTHORS
        all_authors = []
        for authors_list in fic_tracker_df['authors']:
            if isinstance(authors_list, list):
                all_authors.extend(authors_list)

        author_counts = Counter(all_authors)

        top_5_authors = [author for author, _ in author_counts.most_common(5)]

        print("\nTop 5 Authors:")
        if author_counts:
            for author, count in author_counts.most_common(5):
                print(f"- {author}: {count} times")
        else:
            print("No authors found in the tracker.")

        # TOP 5 FANDOMS
        all_fandoms = []
        for fandoms_list in fic_tracker_df['fandoms']:
            if isinstance(fandoms_list, list):
                all_fandoms.extend(fandoms_list)

        fandom_counts = Counter(all_fandoms)

        print("\nTop 5 Fandoms:")
        if fandom_counts:
            for fandom, count in fandom_counts.most_common(5):
                print(f"- {fandom}: {count} times")
        else:
            print("No fandoms found in the tracker.")

        # TOP 5 RELATIONSHIPS
        all_relationships = []
        for relationships_list in fic_tracker_df['relationships']:
            if isinstance(relationships_list, list):
                all_relationships.extend(relationships_list)

        relationship_counts = Counter(all_relationships)

        top_5_relationships = [rel for rel, _ in relationship_counts.most_common(5)]

        print("\nTop 5 Relationships:")
        if relationship_counts:
            for relationship, count in relationship_counts.most_common(5):
                print(f"- {relationship}: {count} times")
        else:
            print("No relationships found in the tracker.")

        # TOP 10 TAGS
        all_free_form_tags = []
        for tags_list in fic_tracker_df['free_form_tags']:
            if isinstance(tags_list, list):
                all_free_form_tags.extend(tags_list)

        tag_counts = Counter(all_free_form_tags)

        print("\nTop 10 Freeform Tags:")
        if tag_counts:
            for tag, count in tag_counts.most_common(10):
                print(f"- {tag}: {count} times")

            top_10_tags = tag_counts.most_common(10)
            tags_1_to_5 = top_10_tags[0:5]
            tags_6_to_10 = top_10_tags[5:10]
        else:
            print("No freeform tags found in the tracker.")
            tags_1_to_5 = []
            tags_6_to_10 = []

        # ---------------------------------------------generate pdf-----------------------------------------------------------------------------------------
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors

        # Define the output PDF filename
        pdf_filename = f'{OUTPUT_DIR}/AO3_Wrapped_Report.pdf'

        # Create a SimpleDocTemplate object
        doc = SimpleDocTemplate(pdf_filename, pagesize=A4)

        # Initialize an empty list called story
        story = []

        # Get the default stylesheet and create custom ParagraphStyle objects
        styles = getSampleStyleSheet()
        styles.add(ParagraphStyle(name='ReportHeading1', fontSize=24, leading=28, alignment=1, spaceAfter=20, fontName='Helvetica-Bold'))
        styles.add(ParagraphStyle(name='ReportHeading2', fontSize=18, leading=22, spaceAfter=10, fontName='Helvetica-Bold'))
        styles.add(ParagraphStyle(name='BodyTextIndent', parent=styles['Normal'], firstLineIndent=0.25*inch, spaceAfter=6))
        styles.add(ParagraphStyle(name='ListBullet', parent=styles['Normal'], leftIndent=0.5*inch, spaceAfter=3))
        if 'BodyText' not in styles:
            styles.add(ParagraphStyle(name='BodyText', parent=styles['Normal'], spaceAfter=6))

        # Add a title to the PDF
        story.append(Paragraph('AO3 Wrapped Report 2026', styles['ReportHeading1']))
        story.append(Spacer(1, 0.2 * inch))

        # Create a section for 'Overall Statistics'
        story.append(Paragraph('Overall Statistics', styles['ReportHeading2']))
        story.append(Paragraph(f"Total Word Count: {total_word_count:,}", styles['BodyText']))
        story.append(Paragraph(f"Total Unique Fics: {total_unique_fics}", styles['BodyText']))
        story.append(Paragraph(f"Average Words Per Day (based on 365 days): {average_words_per_day}", styles['BodyText']))
        story.append(Spacer(1, 0.2 * inch))

        # Add a section for 'Longest Fanfiction'
        story.append(Paragraph('Longest Fanfiction', styles['ReportHeading2']))
        story.append(Paragraph(f"<b>Title:</b> {longest_fic_title}", styles['BodyText']))
        story.append(Paragraph(f"<b>Word Count:</b> {longest_fic_word_count:,}", styles['BodyText']))
        story.append(Paragraph(f"<b>Author:</b> {longest_fic_author}", styles['BodyText']))
        story.append(Paragraph(f"<b>URL:</b> <font color='blue'>{longest_fic_url}</font>", styles['BodyText']))
        story.append(Spacer(1, 0.2 * inch))

        # Add a section for 'Favorite Fanfiction'
        story.append(Paragraph('Favorite Fanfiction', styles['ReportHeading2']))
        story.append(Paragraph(f"<b>Title:</b> {favorite_fic_title}", styles['BodyText']))
        story.append(Paragraph(f"<b>Word Count:</b> {favorite_fic_word_count:,}", styles['BodyText']))
        story.append(Paragraph(f"<b>Author:</b> {favorite_fic_author}", styles['BodyText']))
        story.append(Paragraph(f"<b>URL:</b> <font color='blue'>{favorite_fic_url}</font>", styles['BodyText']))
        story.append(Paragraph(f"<b>Visits:</b> {favorite_fic_visits}", styles['BodyText']))
        story.append(Spacer(1, 0.2 * inch))

        # Create a section for 'Top 5 Authors'
        story.append(Paragraph('Top 5 Authors', styles['ReportHeading2']))
        if author_counts:
            for author, count in author_counts.most_common(5):
                story.append(Paragraph(f"- {author}: {count} times", styles['ListBullet']))
        else:
            story.append(Paragraph("No authors found in the tracker.", styles['BodyText']))
        story.append(Spacer(1, 0.2 * inch))

        # Create a section for 'Top 5 Fandoms'
        story.append(Paragraph('Top 5 Fandoms', styles['ReportHeading2']))
        if fandom_counts:
            for fandom, count in fandom_counts.most_common(5):
                story.append(Paragraph(f"- {fandom}: {count} times", styles['ListBullet']))
        else:
            story.append(Paragraph("No fandoms found in the tracker.", styles['BodyText']))
        story.append(Spacer(1, 0.2 * inch))

        # Create a section for 'Top 5 Relationships'
        story.append(Paragraph('Top 5 Relationships', styles['ReportHeading2']))
        if relationship_counts:
            for relationship, count in relationship_counts.most_common(5):
                story.append(Paragraph(f"- {relationship}: {count} times", styles['ListBullet']))
        else:
            story.append(Paragraph("No relationships found in the tracker.", styles['BodyText']))
        story.append(Spacer(1, 0.2 * inch))

        # 13. Create a section for 'Top 10 Freeform Tags'
        story.append(Paragraph('Top 10 Freeform Tags', styles['ReportHeading2']))
        if tag_counts:
            for tag, count in tag_counts.most_common(10):
                story.append(Paragraph(f"- {tag}: {count} times", styles['ListBullet']))
        else:
            story.append(Paragraph("No freeform tags found in the tracker.", styles['BodyText']))
        story.append(Spacer(1, 0.2 * inch))

        # 14. Build the PDF document
        doc.build(story)
        print(f"\nPDF report generated successfully at: {pdf_filename}")

        # ------------------------------------------------------export to \"output\" folder------------------------------------------------------------
        import shutil
        # os already imported at the top of the cell

        # Define the source path of the generated PDF file
        source_pdf_path = f'{OUTPUT_DIR}/AO3_Wrapped_Report.pdf'

        # Define the destination path \"output\" folder in the Files tab (already defined as destination_drive_path within original 2f196460 cell)
        destination_drive_path = os.path.join(OUTPUT_DIR, 'AO3_Wrapped_Report.pdf')

        # Copy the PDF file to folder
        try:
            shutil.copy(source_pdf_path, destination_drive_path)
            print(f"AO3 Wrapped Report successfully saved to: {destination_drive_path}")
        except Exception as e:
            print(f"Error saving PDF: {e}")

        # -----------------------------------------------------get wrapped images---------------------------------------------------------------------
        from PIL import Image, ImageDraw # ImageDraw needed for drawing text, already imported from PIL

        # ---------- PATH ----------
        PAGE1_TEMPLATE_IMG = f"{ASSETS_DIR}/2026_AO3_Wrapped_Template_Page1.png"

        # ---------- OPEN & SAVE ----------
        img = Image.open(PAGE1_TEMPLATE_IMG)
        img.save(f"{OUTPUT_DIR}/wrapped_page1.png")
        print("Generated wrapped_page1.png")

        # paths
        PAGE2_TEMPLATE_IMG = f"{ASSETS_DIR}/2026_AO3_Wrapped_Template_Page2.png"

        # colors
        WHITE = hex_to_rgb("#f7f7f7") # Moved WHITE and DARK_GRAY here to ensure they are defined in global scope
        DARK_GRAY = hex_to_rgb("#333333")

        # open image
        img = Image.open(PAGE2_TEMPLATE_IMG)
        draw = ImageDraw.Draw(img)

        # draw text (replace variables if needed for testing)
        draw.text((30, 339), f"{total_word_count:,}", font=font_144, fill=WHITE)
        draw.text((30, 660), f"{total_unique_fics}", font=font_120, fill=WHITE)
        draw.text((30, 1090), f"{average_words_per_day}", font=font_80, fill=WHITE)

        # save to temporary output
        img.save(f"{OUTPUT_DIR}/wrapped_page2.png")
        print("Generated wrapped_page2.png")

        # ---------- PATH ----------
        PAGE3_TEMPLATE_IMG = f"{ASSETS_DIR}/2026_AO3_Wrapped_Template_Page3.png"

        # ---------- COLORS ----------
        # DARK_GRAY = hex_to_rgb("#333333") # Already global

        # ---------- OPEN IMAGE ----------
        img = Image.open(PAGE3_TEMPLATE_IMG)
        draw = ImageDraw.Draw(img)

        # ---------- TEXT CONTENT ----------
        fav_title_text = favorite_fic_title
        fav_author_text = f"by {favorite_fic_author}"
        fav_visits_text = f"You visited this fic {favorite_fic_visits} times!"

        # ---------- DRAW CENTERED TEXT ----------

        # Favorite fic title
        draw_wrapped_centered_text(
            draw,
            box=(90, 406, 988, 895),
            text=fav_title_text,
            font=font_72,
            fill=DARK_GRAY,
            line_spacing=12
        )

        # Favorite fic author
        draw_centered_text(
            draw,
            box=(216, 920, 863, 1066),
            text=fav_author_text,
            font=font_40,
            fill=DARK_GRAY
        )

        # Visit count sentence
        draw_centered_text(
            draw,
            box=(35, 1218, 1045, 1318),
            text=fav_visits_text,
            font=font_37,
            fill=DARK_GRAY
        )

        # save to temporary output
        img.save(f"{OUTPUT_DIR}/wrapped_page3.png")
        print("Generated wrapped_page3.png")

        # ---------- PATH ----------
        PAGE4_TEMPLATE_IMG = f"{ASSETS_DIR}/2026_AO3_Wrapped_Template_Page4.png"

        # ---------- OPEN IMAGE ----------
        img = Image.open(PAGE4_TEMPLATE_IMG)
        draw = ImageDraw.Draw(img)

        # ---------- TEXT CONTENT ----------
        top_5_authors_text = "\n".join(
            f"{i+1}. {author}" for i, author in enumerate(top_5_authors)
        )

        # ---------- DRAW TEXT (LEFT-ALIGNED) ----------
        draw.text(
            (180, 282),
            top_5_authors_text,
            font=font_35,
            fill=WHITE,
            spacing=12  # space between lines
        )

        # ---------- SAVE (TEMPORARY) ----------
        img.save(f"{OUTPUT_DIR}/wrapped_page4.png")
        print("Generated wrapped_page4.png")

        # ---------- PATH ----------
        PAGE5_TEMPLATE_IMG = f"{ASSETS_DIR}/2026_AO3_Wrapped_Template_Page5.png"

        # ---------- OPEN IMAGE ----------
        img = Image.open(PAGE5_TEMPLATE_IMG)
        draw = ImageDraw.Draw(img)

        # ---------- TEXT CONTENT ----------
        top_5_relationships_text = "\n".join(
            f"{i+1}. {rel}" for i, rel in enumerate(top_5_relationships)
        )

        # ---------- DRAW TEXT (LEFT-ALIGNED) ----------
        draw.text(
            (128, 374),
            top_5_relationships_text,
            font=font_35,
            fill=WHITE,
            spacing=12
        )

        # ---------- SAVE (TEMPORARY) ----------
        img.save(f"{OUTPUT_DIR}/wrapped_page5.png")
        print("Generated wrapped_page5.png")

        # ---------- PATH ----------
        PAGE6_TEMPLATE_IMG = f"{ASSETS_DIR}/2026_AO3_Wrapped_Template_Page6.png"

        # ---------- OPEN IMAGE ----------
        img = Image.open(PAGE6_TEMPLATE_IMG)
        draw = ImageDraw.Draw(img)

        # ---------- TEXT CONTENT ----------
        tags_1_to_5_text = "\n".join(
            f"{i+1}. {tag}"
            for i, (tag, _) in enumerate(tags_1_to_5)
        )

        tags_6_to_10_text = "\n".join(
            f"{i+6}. {tag}"
            for i, (tag, _) in enumerate(tags_6_to_10)
        )

        # ---------- LEFT COLUMN (1–5) ----------
        draw.text(
            (95, 190),
            tags_1_to_5_text,
            font=font_35,
            fill=DARK_GRAY,
            spacing=20
        )

        # ---------- RIGHT COLUMN (6–10) ----------
        draw.text(
            (84, 815),
            tags_6_to_10_text,
            font=font_35,
            fill=WHITE,
            spacing=20
        )

        # ---------- SAVE (TEMPORARY) ----------
        img.save(f"{OUTPUT_DIR}/wrapped_page6.png")
        print("Generated wrapped_page6.png")

        print("\nAO3 Wrapped report (PDF and PNGs) generated and saved to the output folder!")

print("Defined `on_generate_wrapped_button_clicked` function.")

# --------------------------------------- MANUAL ADD FIC BUTTON ------------------------

import ipywidgets as widgets
from IPython.display import display
import pandas as pd
import ast

# --- Manual Fic Input Widgets ---
manual_url_input = widgets.Text(
    value='',
    placeholder='Enter AO3 URL',
    description='URL:',
    layout={'width': '500px'}
)

manual_title_input = widgets.Text(
    value='',
    placeholder='Enter Fic Title',
    description='Title:',
    layout={'width': '500px'}
)

manual_word_count_input = widgets.IntText(
    value=0,
    description='Word Count:',
    min=0,
    layout={'width': '500px'}
)

manual_authors_input = widgets.Textarea(
    value='',
    placeholder='Comma-separated authors (e.g., Author1, Author2)',
    description='Authors:',
    layout={'width': '500px', 'height': '60px'}
)

manual_ratings_input = widgets.Textarea(
    value='',
    placeholder='Comma-separated ratings (e.g., Teen And Up Audiences)',
    description='Ratings:',
    layout={'width': '500px', 'height': '60px'}
)

manual_warnings_input = widgets.Textarea(
    value='',
    placeholder='Comma-separated archive warnings (e.g., No Archive Warnings Apply)',
    description='Warnings:',
    layout={'width': '500px', 'height': '60px'}
)

manual_category_input = widgets.Textarea(
    value='',
    placeholder='Comma-separated categories (e.g., M/M)',
    description='Category:',
    layout={'width': '500px', 'height': '60px'}
)

manual_fandoms_input = widgets.Textarea(
    value='',
    placeholder='Comma-separated fandoms (e.g., Harry Potter - J. K. Rowling)',
    description='Fandoms:',
    layout={'width': '500px', 'height': '60px'}
)

manual_relationships_input = widgets.Textarea(
    value='',
    placeholder='Comma-separated relationships (e.g., Harry Potter/Draco Malfoy)',
    description='Relationships:',
    layout={'width': '500px', 'height': '60px'}
)

manual_characters_input = widgets.Textarea(
    value='',
    placeholder='Comma-separated characters (e.g., Harry Potter, Draco Malfoy)',
    description='Characters:',
    layout={'width': '500px', 'height': '60px'}
)

manual_freeform_tags_input = widgets.Textarea(
    value='',
    placeholder='Comma-separated freeform tags (e.g., Angst with a Happy Ending)',
    description='Freeform Tags:',
    layout={'width': '500px', 'height': '60px'}
)

manual_add_button = widgets.Button(
    description='Add Fic Manually',
    button_style='primary' # 'success', 'info', 'warning', 'danger' or ''
)

manual_output_widget = widgets.Output()

def parse_comma_separated_string(s):
    """Helper to parse a comma-separated string into a list, stripping whitespace."""
    if not s or s.strip() == '':
        return []
    return [item.strip() for item in s.split(',') if item.strip()]

def add_manual_fic_to_tracker(button):
    with manual_output_widget:
        manual_output_widget.clear_output()
        print("Adding fic manually...")

        global fic_tracker_df, tracker_file_path, list_columns

        fic_details = {
            'url': manual_url_input.value.strip(),
            'title': manual_title_input.value.strip(),
            'word_count': manual_word_count_input.value,
            'authors': parse_comma_separated_string(manual_authors_input.value),
            'ratings': parse_comma_separated_string(manual_ratings_input.value),
            'archive_warnings': parse_comma_separated_string(manual_warnings_input.value),
            'category': parse_comma_separated_string(manual_category_input.value),
            'fandoms': parse_comma_separated_string(manual_fandoms_input.value),
            'relationships': parse_comma_separated_string(manual_relationships_input.value),
            'characters': parse_comma_separated_string(manual_characters_input.value),
            'free_form_tags': parse_comma_separated_string(manual_freeform_tags_input.value)
        }

        if not fic_details['url'] or not fic_details['title']:
            print("Error: URL and Title are required fields.")
            return

        # Use reindex to ensure the Series has all columns of fic_tracker_df
        new_fic_series = pd.Series(fic_details).reindex(fic_tracker_df.columns)

        # Append new Series as a new row to the DataFrame
        fic_tracker_df = pd.concat([fic_tracker_df, pd.DataFrame([new_fic_series])], ignore_index=True)

        # Save the updated DataFrame to CSV
        df_to_save = fic_tracker_df.copy()
        for col in list_columns:
            if col in df_to_save.columns:
                df_to_save[col] = df_to_save[col].apply(lambda x: str(x) if isinstance(x, list) else x)

        df_to_save.to_csv(tracker_file_path, index=False)
        print(f"Successfully added fic '{fic_details['title']}' to tracker. Updated tracker saved to {tracker_file_path}.")

        # Clear input fields after successful submission
        manual_url_input.value = ''
        manual_title_input.value = ''
        manual_word_count_input.value = 0
        manual_authors_input.value = ''
        manual_ratings_input.value = ''
        manual_warnings_input.value = ''
        manual_category_input.value = ''
        manual_fandoms_input.value = ''
        manual_relationships_input.value = ''
        manual_characters_input.value = ''
        manual_freeform_tags_input.value = ''

print("Manual fic input UI initialized.")

"""# ADD FICS TO TRACKER!"""

add_fic_button.on_click(on_add_fic_button_clicked)
generate_wrapped_button.on_click(on_generate_wrapped_button_clicked)

display(ao3_url_textarea, add_fic_button, generate_wrapped_button, output_widget)

"""# ADD FICS MANUALLY"""

# Attach the handler to the button
manual_add_button.on_click(add_manual_fic_to_tracker)

display(
    manual_url_input,
    manual_title_input,
    manual_word_count_input,
    manual_authors_input,
    manual_ratings_input,
    manual_warnings_input,
    manual_category_input,
    manual_fandoms_input,
    manual_relationships_input,
    manual_characters_input,
    manual_freeform_tags_input,
    manual_add_button,
    manual_output_widget
)